### ISSUE TITLE
java 编译时候会将引用常量直接赋值到代码中，导致混淆无效

### ISSUE THREAD

**Issue by Caij** [heruoxin/Robfuscate#4]
https://stackoverflow.com/questions/5173372/java-static-final-values-replaced-in-code-when-compiling/5174142#5174142

比如:
R.string.test = 0x7000001
代码为 getString(R.sting.test)
编译后 getString(0x7000001)

经过测试 所以通过这种是无效的

**Comment by heruoxin** [comment]
你好，抱歉忘记注明，此项目仅对各 module 中的 R 有效。对于采用的单一 module 方式开发的工程，目前没有很好的混淆办法。

稍后会更新 README。
